# Generated by Django 4.1.1 on 2022-11-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_in',
            name='education',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='log_in',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='log_in',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='log_in',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='log_in',
            name='phone_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='log_in',
            name='place',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
